#!/data/data/com.termux/files/usr/bin/bash
echo "📱 CUSTOM ANDROID APP — JARVIS NATIVE"
echo "============================================================"
echo ""
echo "📋 To build a native Jarvis Android app:"
echo ""
echo "Step 1: Install Flutter"
echo "  git clone https://github.com/flutter/flutter.git -b stable"
echo "  export PATH=\"\$PATH:\$(pwd)/flutter/bin\""
echo ""
echo "Step 2: Create the app"
echo "  flutter create jarvis_app"
echo "  cd jarvis_app"
echo ""
echo "Step 3: Copy the main.dart template"
echo "  cp ~/jarvis-android-app/main.dart lib/main.dart"
echo ""
echo "Step 4: Add dependencies"
echo "  flutter pub add http"
echo ""
echo "Step 5: Build the app"
echo "  flutter build apk"
echo ""
echo "Step 6: Install on phone"
echo "  flutter install"
echo ""
echo "✅ Custom Android App guide created"
