#!/data/data/com.termux/files/usr/bin/bash
echo "🎨 LOCAL IMAGE GENERATION"
echo "============================"
echo ""
echo "Option 1: Use AI Horde (already working)"
echo "  ~/bin/use_agent aihorde SDXL 1.0 'draw a cat'"
echo ""
echo "Option 2: Install Stable Diffusion locally"
echo "  git clone https://github.com/Stability-AI/stablediffusion.git"
echo "  cd stablediffusion && pip install -r requirements.txt"
echo "  python scripts/txt2img.py --prompt 'a cat'"
echo ""
echo "Option 3: Use Ollama with image models"
echo "  ollama pull llava"
echo "  ollama run llava 'Describe this image'"
