#!/data/data/com.termux/files/usr/bin/bash
echo "⚡ SHIZUKU + RISH SETUP"
echo "============================"
echo ""
echo "Step 1: Install Shizuku app"
echo "  Download: https://shizuku.rikka.app"
echo ""
echo "Step 2: Enable Wireless Debugging"
echo "  Settings → Developer Options → Wireless Debugging"
echo ""
echo "Step 3: Pair and start Shizuku"
echo "  Open Shizuku app → Pairing via Wireless Debugging"
echo ""
echo "Step 4: Place rish files"
echo "  Download from: https://github.com/RikkaApps/Shizuku-API/releases"
echo "  Place in ~/storage/downloads/"
echo ""
echo "Step 5: Run Shizuku"
echo "  adb shell sh /sdcard/Android/data/moe.shizuku.privileged.api/start.sh"
echo ""
echo "✅ Shizuku setup guide ready"
